services:

  backend:
    build: ./
    container_name: backend
    restart: always
    command:
      - ../commands/${RUN_MODE}.sh
    ports:
      - "8013:${PORT}"
    volumes:
      - ./src:/project/src
      - ./commands:/project/commands
      - static_content:/var/www/web_cheatsheets
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.${RUN_MODE}
    depends_on:
      - postgresql
    env_file:
      - .env


  postgresql:
    image: "postgres:16-alpine"
    container_name: postgresql
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/web_cheatsheets
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data: {}
  static_content: {}
