# Generated by Django 5.1.1 on 2024-10-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='source.source'),
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(max_length=7000),
        ),
    ]
