# Generated by Django 5.1.1 on 2024-10-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_information_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(blank=True, max_length=8000),
        ),
    ]
