# Generated by Django 5.1.1 on 2024-10-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_action_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Change Password'), (3, 'Change Profile'), (4, 'Change Profile image')], default=0),
        ),
    ]
